const swaggerAutogen = require('swagger-autogen')()


const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:8000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "User",
            "description": "Endpoints"
        }
    ],
    securityDefinitions: {
        apiKeyAuth:{
            type: "apiKey",
            in: "header",       // can be "header", "query" or "cookie"
            name: "X-API-KEY",  // name of the header, query parameter or cookie
            description: "any description..."
        }
    },
    definitions: {
        User: {
            name: "John Doe",
            email: "doe@mail.ee"
        },
        AddUser: {
            $name: "John Doe",
            email: "doe@mail.ee",
            password: "1231"
        }
    }
}

const outputFile = './swagger-output.json'
const endpointsFiles = ['./dist/src/app.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./dist/src/app')           // Your project's root file
})
