image: node:22

pipelines:
  default:
    - step:
        name: Install Dependencies
        caches:
          - node
        script:
          - npm install

    - step:
        name: Run Tests
        script:
          - npm test

    - step:
        name: Build Application
        script:
          - npm run build

  branches:
    master:
      - step:
          name: Deploy to Production
          deployment: production
          script:
            - echo "Deploying to production..."
            - npm run deploy
