
const BRACKET_SYMBOL = '\u2500';
const STICK_SYMBOL = '\u2502';
const UNDRERLINE_SYMBOL = '\u251C';
const DOUBLE_BRACKET_SYMBOL = '\u2514';
const STEP = 3;

module.exports = {BRACKET_SYMBOL, STICK_SYMBOL, UNDRERLINE_SYMBOL, DOUBLE_BRACKET_SYMBOL, STEP};